services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181 
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
      
kafka:
  image: confluentinc/cp-kafka:7.4.0
  # ...
  environment:
    KAFKA_BROKER_ID: 1 
    KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181' # Используется, но не всегда достаточно

    # *** КРИТИЧЕСКОЕ ИЗМЕНЕНИЕ ДЛЯ 7.x ***
    # 1. Какие адреса слушать (слушаем на всех IP)
    KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
    
    # 2. Какие адреса рекламировать клиентам
    KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
    
    # 3. Настройка протокола
    KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
    KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    
    # 4. Включение создания тем (для удобства лабы)
    KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    
    # 5. Стандартные параметры
    KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    KAFKA_LOG_RETENTION_MS: 1000 

  api:
    build: ./api 
    ports:
      - "8000:8000" 
    environment:
      - KAFKA_HOST=kafka:29092 
      - KAFKA_TOPIC=LAB4    
    depends_on:
      - kafka

  worker:
    build: ./worker
    environment:
      - KAFKA_HOST=kafka:29092
      - KAFKA_TOPIC=LAB4    
      - KAFKA_GROUP=worker_group 
    depends_on:
      - kafka
    deploy:
      mode: replicated 
      replicas: 5